### ISSUE TITLE
"Loading stop schedules ..." 

### ISSUE THREAD

**Issue by FazCodeFR** [LoneWanderer-GH/MMM-Toulouse-Transports#6]
Bonjour, 
Je parle en français mais si vous voulez je peux parler en anglais,
Merci tout d'abord pour se module !
J'ai un problème que je n'arrive pas a résoudre,
"Loading stop schedules ..." a infini

Dans MMM-Toulouse-Transports.js j'ai : 
`            config: {
                apiKey: 'MA CLE ICI',
                stopSchedules: [
                    {
                        lineNumber: 19, // shall be >0
                        stopCode: 1991, // shall be >0
                        maxEntries:2    // shall be >1
                    }
                ],
                debug: true,
                updateInterval: 120000
            }
        }`

stopCode c'est bien le numéro d’arrêt du bus et lineNumber le numéro du bus ?

Sinon je vois pas ou est le problème 
Merci beaucoup ! @LoneWanderer-GH

**Comment by LoneWanderer-GH** [comment]
Bonjour,
J'ai arrêté l'utilisation de mon module il y a quelques temps.
Il faudra que je réalise une install complète et que je regarde si je peux reproduire le problème.

Avez vous des données de logs utiles à me fournir ?

**Comment by LoneWanderer-GH** [comment]
Je viens de refaire une installation propre sur mon pi.

Cela fonctionne chez moi.

A noter qu'au démarrage, il y a un premier délai qui peut être déroutant. Il correspond à une première échéance de la fréquence de mise à jour :
`updateInterval: 120000`

Vous pouvez raccourcir ce délai si besoin.

J'ai commencé à prototyper qqchose pour raccourcir ce délai, je vais voir pour rapatrier ça sur la branche principale.

**Comment by LoneWanderer-GH** [comment]
Vous pouvez tester a nouveau a partir de la branche master (reinstallation) ?
Branches possibles : #5  (ou #7 qui a été mergée dans #5)

![working_mmm-toulouse_transports](https://user-images.githubusercontent.com/19716859/48215846-72244280-e383-11e8-85ea-a719da97e01a.png)

**Comment by LoneWanderer-GH** [comment]
Closing issue until further notice.

**Comment by FazCodeFR** [comment]
Le problème semble pas réglé malheureusement, j'ai bien mis a jour le dossier MMM-Toulouse-Transports (supprimer l’ancien puis git clone le nouveau et npm install

Se que ça affiche :
![image](https://user-images.githubusercontent.com/30906528/48296327-a25c0600-e495-11e8-9fd0-7c7ff81a4da5.png)


Voici ma configuration

Le fichier config :
![image](https://user-images.githubusercontent.com/30906528/48296297-501ae500-e495-11e8-97b4-78a1211c779e.png)

Le fichier config de MMM-Toulouse-Transports :
![image](https://user-images.githubusercontent.com/30906528/48296313-793b7580-e495-11e8-9a2d-137953525474.png)


Merci d'avance

**Comment by FazCodeFR** [comment]
Je viens de réussir ! 
Ahaha j'avais cru qu'il fallais modifier le fichier MMM-Toulouse-Transports.js alors que non (surtout que c'était du commentaire ...)
Je viens de mettre la config faite de MMM-Toulouse-Transports.js sur config.js, ça marche nickel merci beaucoup en espérant que mon erreur aident d'autres personnes !
Super plugin en tout cas merci beaucoup !

**Comment by xshuffl3x** [comment]
Bonjour,

J'ai également le problème de loading stop schedules.

Le stop code, je l'ai pris directement sur l'arrêt de bus en passant devant un matin.
mon exemple c'est l'arrêt douanes direction basso ligne 14 et 46.

Je pense qu'il y a un truc qui m'échappe car il me semble avoir bien config mon fichier config.js
![capture d ecran 2019-02-15 a 00 51 36](https://user-images.githubusercontent.com/47647871/52825177-0822e400-30bc-11e9-9e86-75c8a3016bbe.jpg)

Est-ce qu'il y a une config à faire dans le fichier MMM-Toulouse-Transports.js ?

Les instructions n'en parlent pas... Désolé de réveiller ce post mais ça fait 1 semaines que je cherche. #noobinside 😅

Dans mon cas on est d'accord que je trouve mon ID d'arrêt de bus ici : 
https://data.toulouse-metropole.fr/explore/dataset/arrets-de-bus0/table/?q=douanes&dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6ImFycmV0cy1kZS1idXMwIiwib3B0aW9ucyI6eyJxIjoiZG91YW5lcyJ9fSwiY2hhcnRzIjpbeyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoiY29sdW1uIiwiZnVuYyI6IkFWRyIsInlBeGlzIjoic2VucyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoic2VucyIsIm1heHBvaW50cyI6NTAsInNvcnQiOiIifV0sInRpbWVzY2FsZSI6IiIsImRpc3BsYXlMZWdlbmQiOnRydWUsImFsaWduTW9udGgiOnRydWV9&location=22,43.57446,1.39711&basemap=jawg.streets

Merci !

**Comment by bleusswissbless** [comment]
Bonjour messieurs,
Comme toi xshuffl3x ça ne fonctionne pas :(
j'ai réinstallé, copier/coller le bloc de conf du fichier js, tenté plusieurs syntaxes l7, L7, avec des simples cotes, des doubles cotes, plus de virgules, moins de virgules, j'en peu plus j'arrête ! même avec la conf proposé par défaut ça ne veux pas. Voici ce que le debug mode donne en boucle !
si quelqu'un à une idée de ce qui peut se passer ? je viens d'écrire à Tisseo pour leur demander de vérifier ma clé.
merci :)

````
Connecting socket for: MMM-Toulouse-Transports
ERROR MMM-Toulouse-Transports - logger - configuration NOT SET YET. Logging anyway.
TRACE MMM-Toulouse-Transports - start - start
ERROR MMM-Toulouse-Transports - logger - configuration NOT SET YET. Logging anyway.
TRACE MMM-Toulouse-Transports - start - busScheduleData.lastUpdate Sat Feb 16 2019 15:55:47 GMT+0100 (CET)
ERROR MMM-Toulouse-Transports - logger - configuration NOT SET YET. Logging anyway.
TRACE MMM-Toulouse-Transports - start - busScheduleData.lastUpdate minus 01h00 Sat Feb 16 2019 14:55:47 GMT+0100 (CET)
ERROR MMM-Toulouse-Transports - logger - configuration NOT SET YET. Logging anyway.
TRACE MMM-Toulouse-Transports - start - end
...
ERROR MMM-Toulouse-Transports - logger - configuration NOT SET YET. Logging anyway.
TRACE MMM-Toulouse-Transports - socketNotificationReceived - received: SET_CONFIG
DEBUG MMM-Toulouse-Transports -  *** config set in node_helper: 
DEBUG MMM-Toulouse-Transports - {"maxTimeOffset":200,"useRealtime":true,"updateInterval":120000,"animationSpeed":2000,"convertToWaitingTime":true,"initialLoadDelay":0,"apiBaseSchedules":"https://api.tisseo.fr/v1/stops_schedules.json?","maxLettersForDestination":22,"concatenateArrivals":true,"showSecondsToNextUpdate":true,"showLastUpdateTime":false,"oldUpdateOpacity":0.5,"oldThreshold":0.1,"retryDelay":1000,"debug":true,"apiKey":"fff0f265*******5f4","stopSchedules":[{"lineNumber":"l7","stopCode":6601,"maxEntries":2}]}
TRACE MMM-Toulouse-Transports - socketNotificationReceived - received: UPDATE_GLOBAL_TISSEO_DATA
TRACE MMM-Toulouse-Transports -  *** call Update Lines list
TRACE MMM-Toulouse-Transports - updateAllTisseoData - start
DEBUG MMM-Toulouse-Transports - updateAllTisseoData - itreations to do: 1
TRACE MMM-Toulouse-Transports - updateLineInfo - start
DEBUG MMM-Toulouse-Transports - updateLineInfo - iteration:0 get Line data for: l7
TRACE MMM-Toulouse-Transports - updateLineInfo - end
TRACE MMM-Toulouse-Transports - updateAllTisseoData - end
TRACE MMM-Toulouse-Transports - updateBusScheduleTimetable - start - parameter: index=0
DEBUG MMM-Toulouse-Transports - updateBusScheduleTimetable - not all relevant Tisseo Data is present ==> reschedule
DEBUG MMM-Toulouse-Transports - updateBusScheduleTimetable - self.loaded=function (callback) {
		console.log("Module helper loaded: " + this.name);
		callback();
	}
DEBUG MMM-Toulouse-Transports - updateBusScheduleTimetable - this.config.retryDelay=1000
TRACE MMM-Toulouse-Transports - processBusScheduleDataPending - start
DEBUG MMM-Toulouse-Transports - processBusScheduleDataPending - sending the data to MM module. Data: 
DEBUG MMM-Toulouse-Transports - processBusScheduleDataPending - {"lastUpdate":"2019-02-16T14:55:53.717Z","loaded":false,"currentUpdateInterval":1000}
TRACE MMM-Toulouse-Transports - processBusScheduleDataPending - end
TRACE MMM-Toulouse-Transports - scheduleBusScheduleUpdate - start - asked delay: 1000
TRACE MMM-Toulouse-Transports - scheduleBusScheduleUpdate - effecive next load is programmed in 1000
TRACE MMM-Toulouse-Transports - scheduleBusScheduleUpdate - end
TRACE MMM-Toulouse-Transports - updateBusScheduleTimetable - end
TRACE MMM-Toulouse-Transports - socketNotificationReceived - schedule update of bus data (call scheduleBusScheduleUpdate())
TRACE MMM-Toulouse-Transports - scheduleBusScheduleUpdate - start - asked delay: 0
TRACE MMM-Toulouse-Transports - scheduleBusScheduleUpdate - effecive next load is programmed in 0
TRACE MMM-Toulouse-Transports - scheduleBusScheduleUpdate - end
Create new news fetcher for url: https://www.azinat.com/feed/ - Interval: 300000
Create new news fetcher for url: https://www.lemonde.fr/rss/une.xml - Interval: 300000
Create new news fetcher for url: https://www.courrierinternational.com/feed/category/6268/rss.xml - Interval: 300000
TRACE MMM-Toulouse-Transports - updateBusScheduleTimetable - start - parameter: index=0
DEBUG MMM-Toulouse-Transports - updateBusScheduleTimetable - not all relevant Tisseo Data is present ==> reschedule
DEBUG MMM-Toulouse-Transports - updateBusScheduleTimetable - self.loaded=function (callback) {
		console.log("Module helper loaded: " + this.name);
		callback();
	}
```
