### ISSUE TITLE
Problème de "stop code" ?

### ISSUE THREAD

**Issue by LoneWanderer-GH** [LoneWanderer-GH/MMM-Toulouse-Transports#8]
Bonjour,

J'ai également le problème de loading stop schedules.

Le stop code, je l'ai pris directement sur l'arrêt de bus en passant devant un matin.
mon exemple c'est l'arrêt douanes direction basso ligne 14 et 46.

Je pense qu'il y a un truc qui m'échappe car il me semble avoir bien config mon fichier config.js
![capture d ecran 2019-02-15 a 00 51 36](https://user-images.githubusercontent.com/47647871/52825177-0822e400-30bc-11e9-9e86-75c8a3016bbe.jpg)

Est-ce qu'il y a une config à faire dans le fichier MMM-Toulouse-Transports.js ?

Les instructions n'en parlent pas... Désolé de réveiller ce post mais ça fait 1 semaines que je cherche. #noobinside 😅

Dans mon cas on est d'accord que je trouve mon ID d'arrêt de bus ici : 
https://data.toulouse-metropole.fr/explore/dataset/arrets-de-bus0/table/?q=douanes&dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6ImFycmV0cy1kZS1idXMwIiwib3B0aW9ucyI6eyJxIjoiZG91YW5lcyJ9fSwiY2hhcnRzIjpbeyJhbGlnbk1vbnRoIjp0cnVlLCJ0eXBlIjoiY29sdW1uIiwiZnVuYyI6IkFWRyIsInlBeGlzIjoic2VucyIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoic2VucyIsIm1heHBvaW50cyI6NTAsInNvcnQiOiIifV0sInRpbWVzY2FsZSI6IiIsImRpc3BsYXlMZWdlbmQiOnRydWUsImFsaWduTW9udGgiOnRydWV9&location=22,43.57446,1.39711&basemap=jawg.streets

Merci !

_Originally posted by @xshuffl3x in https://github.com/LoneWanderer-GH/MMM-Toulouse-Transports/issues/6#issuecomment-463851819_

**Comment by LoneWanderer-GH** [comment]
Bonjour,
Je vois un erreur dans la structure JSON que vous montrez. Cette structure devrait être valide :
```
{
    "module": "MMM-Toulouse-Transports",
    "position": "top_right",
    "header": "Horaires de passage",
    "config": {
        "apiKey"         : "YOUR API KEY HERE",
        "debug"          : false,
        "updateInterval" : 60000,
        "stopSchedules"  : [
            {
            "lineNumber": 14,
            "stopCode"  : 2010,
            "maxEntries": 3
            }// il n'y a qu'un seul élément dans le tableau stopSchedules
        ]
    }
}
```

**Comment by xshuffl3x** [comment]
C’est à dire ?
J’ai uniquement copier coller le code 😆

**Comment by LoneWanderer-GH** [comment]
Votre fichier de configuration actuel est le suivant (d'après votre screenshot):
```
{
    "module": "MMM-Toulouse-Transports",
    "position": "top_right",
    "header": "Horaires de passage",
    "config": {
        "apiKey"         : "YOUR API KEY HERE",
        "debug"          : false,
        "updateInterval" : 60000,
        "stopSchedules"  : [
            {
            "lineNumber": 14,
            "stopCode"  : 2010,
            "maxEntries": 3
            },
            {
            // etc. <= ceci génère un bug (c'est un champ vide)
            },
           { // <= ceci est invalide
        ]
    }
}
```
En Javascript, les tableaux sont délimités par des crochets`[]`. Les éléments d'un tableau sont séparés par des virgules `,`. Voir aussi cette doc: [définition W3C d'un tableau Javascript](https://www.w3schools.com/js/js_arrays.asp).
Les éléments d'un tableau Javascript peuvent être n'importe quel entité Javascript valide : objet, structure, tableau (cf. [les types de données Javascript](https://www.w3schools.com/js/js_datatypes.asp)

Le module n'est pas robuste à une structure Javascript incorrecte ou contenant des éléments vides `{}`/incomplets`{lineNumber: 8}`

Essayez cette configuration (tableau de 1 définition d'arrêt):

```
{
    "module": "MMM-Toulouse-Transports",
    "position": "top_right",
    "header": "Horaires de passage",
    "config": {
        "apiKey"         : "YOUR API KEY HERE",
        "debug"          : false,
        "updateInterval" : 60000,
        "stopSchedules"  : [
            {
            "lineNumber": 14,
            "stopCode"  : 2010,
            "maxEntries": 3
            }
        ]
    }
}
```

Si vous voulez ajouter un autre arrêt en plus de votre premier arrêt (tableau de 2 arrêts):

```
{
    "module": "MMM-Toulouse-Transports",
    "position": "top_right",
    "header": "Horaires de passage",
    "config": {
        "apiKey"         : "YOUR API KEY HERE",
        "debug"          : false,
        "updateInterval" : 60000,
        "stopSchedules"  : [
            {
            "lineNumber": 14,
            "stopCode"  : 2010,
            "maxEntries": 3
            },
            {
            "lineNumber": 14,
            "stopCode"  : 123456789,
            "maxEntries": 6
            }
        ]
    }
}
```

**Comment by xshuffl3x** [comment]
Oh merci beaucoup ça fonctionne!

**Comment by LoneWanderer-GH** [comment]
De rien.
Je ferme le ticket.
